### Get all tasks
GET http://localhost:5000/api/tasks
Accept: application/json

### Add a new task
POST http://localhost:5000/api/tasks
Content-Type: application/json

{
  "title": "New Task",
  "description": "This is a new task",
  "status": "pending"
}

### Update a task
PUT http://localhost:5000/api/tasks/{{tasks_id}}
Content-Type: application/json

{
  "title": "Updated Task",
  "description": "This is an updated task description",
  "status": "in-progress"
}

### Delete a task
DELETE http://localhost:5000/api/tasks/{{tasks}}
